# Practica de Algebra lineal

### *Nombre*

<span style="color:blue">Ejercicio 1:  
Usando los procedimientos add y mult_vector_escalar definidos anteriormente, calcular:   
{$\alpha$[1,2]+[3,4] : $\alpha$$\in$$\mathbb{R}$, 0$\leq$$\alpha$$\leq$1, con una precision de dos decimales (para la multiplicación)}</style>

In [ ]:
def mult_vector_escalar(alpha, v):
    return [alpha*v[i] for i in range(len(v))]

[add(mult_vector_escalar(i/100,[1,2]),[3,4]) for i in range(101)]

<span style="color:blue">Ejercicio 2:  
Mortadelo y Filemón usan como clave el siguiente vector:</style>  
> <span style="color:blue">**k**=[0,1,0,0,1,0,1,0,1,0]</style>  

<span style="color:blue">Mortadelo quiere enviarle a Filemón el siguiente mensaje:</style>  
> <span style="color:blue">**p**=[0,0,0,1,1,1,0,1,0,1]</style>  

<span style="color:blue">Mortadelo encripta su mensaje añadiendo k:</style>  
> <span style="color:blue">**c**=**p**+**k**=[0,0,0,1,1,1,0,1,0,1]+[0,1,0,0,1,0,1,0,1,0]=[0,1,0,1,0,1,1,1,1,1]</style>  

<span style="color:blue">Cuando Filemón recibe el mensaje, lo desencripta añadiendo **k** a lo que ha recibido</style>  
> <span style="color:blue">**p**=**c**+**k**=[0,1,0,1,0,1,1,1,1,1]+[0,1,0,0,1,0,1,0,1,0]=[0,0,0,1,1,1,0,1,0,1]</style>    

<span style="color:blue">que es el mensaje original</style>    
  
 <span style="color:blue">¿Cómo lo harías en Python? (Definiendo un procedimiento)</style>  

In [2]:
def addGF(v,w):
    vw = []
    for i in range(len(v)):
        if (v[i] == w[i]):
            vw.append(0)
        else:
            vw.append(1)
    return vw

clave=[0,1,0,0,1,0,1,0,1,0] 

def encriptarMensaje(mens):
    mensEncriptado = addGF(mens, clave)
    return mensEncriptado

def desencriptarMensaje(mensCrip):
    mensDesencriptado = addGF(mensCrip, clave)
    return mensDesencriptado

p = [0,0,0,1,1,1,0,1,0,1] 
Mortadelo = encriptarMensaje(p)
Filemon = desencriptarMensaje(Mortadelo)
print(Filemon) 

[0, 0, 0, 1, 1, 1, 0, 1, 0, 1]


<span style="color:blue">Ejercicio 3: coste total o beneficio. </style>

<span style="color:blue">Supongamos que D es el conjunto de algunos ingredientes de la cerveza: </style>
> <span style="color:blue">D={lúpulo, malta, agua, levadura}</style>  

<span style="color:blue">Por otro lado tenemos el vector coste:</style>  
> <span style="color:blue">coste={lúpulo: 2,5€, malta: 1.5€, agua: 0.006€, levadura: 0,45€}</style>  

<span style="color:blue">Por último tenemos el vector cantidad con lo necesario para hacer una cerveza:</style>  
> <span style="color:blue">cantidad={lúpulo: 6u, malta: 14u, agua: 7u, levadura: 11u}</style>  

<span style="color:blue">¿Cuánto cuesta hacer una cerveza?</style> 

In [4]:
def producto_vectorial(u,v):
    return sum(u[i]*v[i] for i in range(len(u)))

coste={"lupulo":2.5, "malta":1.5, "agua":0.006, "levadura":0.45} 
cantidad={"lupulo": 6, "malta": 14, "agua": 7, "levadura": 11} 

costeCerveza = producto_vectorial(list(coste.values()), list(cantidad.values()))
print (costeCerveza)

40.992000000000004


<span style="color:blue"> Ejercicio 4:   
¿Cómo escribirías cada uno de los vectores {[3,0,0],[0,2,0],[0,0,1]} como combinación lineal de {[2,0,1],[1,0,2],[2,2,2]}?
Escribe las combinaciones lineales en Python. Seguramente tenga que definir una nueva suma.</style>

In [5]:
def addnR3(u,v,w):
    return[u[i]+v[i]+w[i] for i in range(len(u))]

def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

In [6]:
# [2,-1,0] => 2·[2,0,1]+(-1)·[1,0,2]+0·[2,2,2]
addnR3(mult_vector_escalar(2,[2,0,1]),mult_vector_escalar(-1,[1,0,2]),mult_vector_escalar(0,[2,2,2]))

[3, 0, 0]

In [7]:
# [-2/3,-2/3,1] => -2/3·[2,0,1]+(-2/3)·[1,0,2]+1·[2,2,2]
addnR3(mult_vector_escalar(-2/3,[2,0,1]),mult_vector_escalar(-2/3,[1,0,2]),mult_vector_escalar(1,[2,2,2]))

[0.0, 2.0, 0.0]

In [8]:
# [-1/3,2/3,0] => -1/3·[2,0,1]+(2/3)·[1,0,2]+0·[2,2,2]
addnR3(mult_vector_escalar(-1/3,[2,0,1]),mult_vector_escalar(2/3,[1,0,2]),mult_vector_escalar(0,[2,2,2]))

[0.0, 0.0, 1.0]

<span style="color:blue"> Ejercicio 5:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [9]:
import numpy as np

A=np.matrix([
    [2,-3],
    [-4,6]
])

B=np.matrix([
    [8,4],
    [5,5]
])

A*B

matrix([[ 1, -7],
        [-2, 14]])

In [10]:
import numpy as np

A=np.matrix([
    [2,-3],
    [-4,6]
])

C=np.matrix([
    [5,-2],
    [3,1]
])

A*C

matrix([[ 1, -7],
        [-2, 14]])

In [11]:
import numpy as np

B=np.matrix([
    [8,4],
    [5,5]
])

C=np.matrix([
    [5,-2],
    [3,1]
])

B == C

matrix([[False, False],
        [False, False]])

<span style="color:blue"> Ejercicio 6 :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

In [12]:
# Creamos matriz B con 4 incógnitas para crear un sistema de 4 ecuaciones con 8 incógnitas:
# 3x-6z = 0
# 3y -6W = 0
# -x +2Z = 0
# -y + 2w = 0
# Resolvemos el sistema de ecuaciones y una de las posibles soluciones es la matriz B definida abajo. Probamos el producto
# y verificamos que la multiplicacion de las matrices es la matriz cero y se cumple que las columnas de B no son iguales
# entre si y son distintas de cero.

import numpy as np

A=np.matrix([
    [3,-6],
    [-1,2]
])

B=np.matrix([
    [2,4],
    [1,2]
])

A*B

matrix([[0, 0],
        [0, 0]])

<span style="color:blue"> Ejercicio 7:  
Sarrus para el determinante de orden 3.  
¿Cómo lo haríamos en Python?</style>

In [13]:
# Regla de Cramer para el determinante de orden 3

import numpy as np
A=np.matrix([
    [1,-4,2],
    [-2,8,-9],
    [-1,7,0]
])

x = 0
y = 0
for i in range (0,3):
    x = x + (A[0,i]) * (A[1,(i+1)%3]) * (A[2,(i+2)%3])
    y = y + (A[2,i]) * (A[1,(i+1)%3]) * (A[0,(i+2)%3])

print ("Determinante = ", x-y)


Determinante =  15


<span style="color:blue"> Ejercicio 8:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [14]:
import numpy as np
A=np.matrix([
    [1,-2,1],
    [0,2,8],
    [-4,5,9]
])
rangoA=np.linalg.matrix_rank(A)
print ("El rango de la matriz es: ",rangoA)

El rango de la matriz es:  3


> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [15]:
import numpy as np
A=np.matrix([
    [0,1,-4],
    [2,3,2],
    [-5,8,7]
])
rangoA=np.linalg.matrix_rank(A)
print ("El rango de la mmatriz es: ",rangoA)

El rango de la mmatriz es:  3


> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [16]:
import numpy as np
A=np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])
rangoA=np.linalg.matrix_rank(A)
print ("El rango de la mmatriz es: ",rangoA)

El rango de la mmatriz es:  2


<span style="color:blue"> Ejercicio 9:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

<span style="color:blue"> Ejercicio 10:  
¿Cuál es la representación coordenada del vector v= [6, 3, 2, 5] en términos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1]?</style> 

In [17]:
[2,2,-1]

[2, 2, -1]

<span style="color:blue"> Ejercicio 11:  
Supongamos que queremos diseñar la red de internet para el otro campus universitario.  
La red debe lograr la misma conectividad que el grafo de entrada.  
Una arista representa un posible cable.  
El peso de la arista es el coste de instalar el cable.  
Nuestro objetivo es minimizar el coste total, usando el algoritmo Grow y el algoritmo Shrink.  </style> 

- Método de Grow:
    Colocamos las aristas en orden creciente según sus pesos: 2, 7, 9. Empezamos por la primera arista: {Pembroke Campus,
Bio-Med} y la añadimos a S. Tenemos que añadir el nodo Athletic Complex. Podemos ir desde Pembroke Campus (coste 7) o desde
Bio-Med (coste 9). Así que cogemos la primera opción y la añadimos a S.

S = {{Pembroke Campus, Bio-Med}, {Pembroke Campus, Athletic Complex}}

- Método de Shrink
    Colocamos las aristas en orden decreciente según sus pesos: 9, 7, 2.
La arista que más peso tiene es {Athletic Complex, Bio-Med}:9. Si la quito podríamos seguir yendo a todos los nodos. El 
siguiente paso es quitar la siguiente arista de más peso que no podemos quitar porque entonces tendríamos un node incomunicado.

S = {{Pembroke Campus, Bio-Med}, {Pembroke Campus, Athletic Complex}}

<span style="color:blue"> Ejercicio 12:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$. Calcular el rango por filas y por columnas usando Python.</style> 

In [18]:
import numpy as np
M=np.matrix([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])
rangoM=np.linalg.matrix_rank(M)
rangoM

3

In [19]:
import numpy as np
M=np.matrix([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])
MT=np.transpose(M)
rangoMT=np.linalg.matrix_rank(MT)
rangoMT

3

<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

<span style="color:blue"> Ejercicio 14:  
Modificar lo necesario en los algoritmos para que funcionen y calculen el problema de la casa en llamas.</style>

In [20]:
def calcSigma (a,b):
    return np.sum(np.multiply(a,b))/np.sum(np.multiply(a,a))

def puntoMasCercanoAPtoB(sigma,a):
    return sigma*np.array(a)

def distanciaAptoB(ptoB,b):
    return(np.linalg.norm(np.subtract(b, ptoB)))
 
import numpy as np
a=np.array([[6,2]])
b=np.array([[2,4]])

sigma = calcSigma(a,b)
calcPuntoMasCercanoAPtoB = puntoMasCercanoAPtoB(sigma,a)
print ("Punto mas cercano a b es: ", calcPuntoMasCercanoAPtoB)
distanciaAB =distanciaAptoB(calcPuntoMasCercanoAPtoB,b)
print ("La distancia a pto B es: ", distanciaAB)

## Como la distancia a la casa es < 3,5 => la casa se salva

Punto mas cercano a b es:  [[3. 1.]]
La distancia a pto B es:  3.1622776601683795
